NameProvider: hostname
Compute:
  Enabled: true
  Orchestrators:
    - 127.0.0.1:4222
  Env:
    AllowList:
      - "AWS_*"
      - "REGION"
      - "HOSTNAME"
  AllowListedLocalPaths:
    - "/app/**:rw"

UpdateConfig:
  Interval: 0 